package com.ormconfig.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

@Entity                //(name = "cars")
@Table(name = "cars")  // table name if diffrenet than classname
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Car {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // hybernet will create the id for us in the table
    private int id;

    private String make;
    private String model;


    public Car(String make, String model) { //id will be generated by spring
        this.make = make;
        this.model = model;
    }
}
